server:
  context-path: /registration
  port: 8448
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: /java/MHC_LOGS/registration/registration.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    gov:
      samsha:
        registration: ERROR
security:
  basic:
    enabled: false
spring.jmx:
  enabled: false
spring.oauth2:
  client:
    clientId: registration
security.oauth2:
  resource:
    id: registration
    jwt:
      key-value:  |
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
    userInfoUri: https://localhost:8443/uaa/userinfo
oauth:
  server:
    uaa: https://localhost:8443/uaa
  resources:
    phr: https://localhost:8445/phr