server:
  port: 8448
logging:
  file: /java/C2S_LOGS/patient-registration/patient-registration.log
info:
  component: Patient Registration API
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      # endpoint for discovery-server, pass '--eureka.client.protocol=https' if discovery-server is running on https
      defaultZone: ${eureka.client.protocol:http}://localhost:8761/eureka/
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: registration
    resource:
      jwt:
        # public key to validate the token signed by authorization server
        key-value: |
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
identifier:
  mrnPrefix: C2S-DEV
  # Domain OID for C2S MRN
  mrnDomainId: 1.3.6.1.4.1.21367.13.20.200
  # ID Type for C2S MRN
  mrnDomainType: ISO
  mrnDomainLabel: Consent2Share
  mrnIdLength: 6
  mrnSystem: http://www.goodhealth.org/identifiers/mrn
  mrnUse: usual
  ssnSystem: http://hl7.org/fhir/v2/0203
  ssnLabel: SSN
hie-connection:
  fhir:
    enabled: false
    #serverUrl: http://fhirtest.uhn.ca/baseDstu3
    serverUrl: http://localhost:8080/iexhub/services
    fhirClientSocketTimeoutInMs: 768000
---
# enables ssl in this service when activated
spring.profiles: ssl
server:
  port: 8448
  # configure keystore and keystore password for ssl per environment
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
# enables ssl and adds /patientRegistration context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /patientRegistration
---
# updates configuration for docker environment
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: ${eureka.client.protocol:http}://discovery-server.c2s.com:8761/eureka/
  instance:
    prefer-ip-address: true
fhir:
  serverUrl: http://iexhub.c2s.com:8080/iexhub/services
