server:
  port: 8448
logging:
  file: /java/C2S_LOGS/patient-registration/patient-registration.log
info:
  component: Patient Registration API
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
security:
  oauth2:
    client:
      client-id: registration
identifier:
  mrnPrefix: C2S-DEV
  # Domain OID for C2S MRN
  mrnDomainId: 1.3.6.1.4.1.21367.13.20.200
  # ID Type for C2S MRN
  mrnDomainType: ISO
  mrnDomainLabel: Consent2Share
  mrnIdLength: 6
  mrnSystem: https://bhits.github.io/consent2share/
  mrnUse: usual
  ssnSystem: http://hl7.org/fhir/sid/us-ssn
  ssnLabel: SSN
hie-connection:
  fhir:
    enabled: false
    serverUrl: http://localhost:8080/iexhub/services
    fhirClientSocketTimeoutInMs: 768000
---
# enables ssl and adds /patientRegistration context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /patientRegistration
---
# updates configuration for docker environment
spring:
  profiles: docker
fhir:
  serverUrl: http://iexhub.c2s.com:8080/iexhub/services
