server:
  port: 8448
logging:
  file: /java/MHC_LOGS/registration/registration.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    gov:
      samhsa:
        mhc:
          patientregistration: info
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: registration
      access-token-uri: https://localhost:8443/uaa/oauth/token
    resource:
      jwt:
        key-value: |
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
info:
  component: Patient Registration API
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
identifier:
  mrnPrefix: C2S-DEV
  mrnDomainId: 1.3.6.1.4.1.21367.13.20.200
  mrnDomainType: ISO
  mrnDomainLabel: Consent2Share
  mrnIdLength: 6
  mrnSystem: http://www.goodhealth.org/identifiers/mrn
  mrnUse: usual
  ssnSystem: http://hl7.org/fhir/v2/0203
  ssnLabel: SSN
hie-connection:
  fhir:
    enabled: false
    serverUrl: https://localhost:8443/iexhub/services
    fhirClientSocketTimeoutInMs: 768000
---
spring.profiles: ssl
server:
  port: 8448
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /patientRegistration
---
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true
fhir:
  serverUrl: https://iexhub.mhc.com:8443/iexhub/services
