server:
  context-path: /registration
  port: 8448
  ssl:
    key-store: c:/ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: C:/java/MHC_LOGS/registration/registration.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    gov:
      samsha:
        registration: ERROR
security:
  basic:
    enabled: false
spring.jmx:
  enabled: false
spring.oauth2:
  client:
    clientId: registration
security.oauth2:
  resource:
    id: registration
    jwt.keyUri: https://localhost:8443/uaa/token_key
    userInfoUri: https://localhost:8443/uaa/userinfo
oauth:
  server:
    uaa: https://localhost:8443/uaa
  resources:
    phr: https://localhost:8445/phr