server.port: 8087
logging:
  file: C:/java/PP_LOGS/registration/registration.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    gov:
      samsha:
        registration: ERROR
security:
  basic:
    enabled: false
spring.jmx:
  enabled: false
spring.oauth2:
  client:
    clientId: registration
security.oauth2:
  resource:
    id: registration
    jwt.keyUri: http://localhost:8080/uaa/token_key
    userInfoUri: http://localhost:8080/uaa/userinfo
oauth:
  server:
    uaa: http://localhost:8080/uaa
  resources:
    phr: http://localhost:8080/phr