spring:
  profiles:
    active: docker
server:
  context-path: /registration
  port: 8448
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: /java/MHC_LOGS/registration/registration.log
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    gov:
      samsha:
        patientregistration: ERROR
security:
  basic:
    enabled: false
spring.jmx:
  enabled: false
spring.oauth2:
  client:
    clientId: registration
security.oauth2:
  resource:
    id: registration
    jwt:
      key-value:  |
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
    userInfoUri: https://localhost:8443/uaa/userinfo
oauth:
  server:
    uaa: https://localhost:8443/uaa
  resources:
    phr: https://localhost:8445/phr
identifier:
  mrnPrefix: MHC-DEV
  mrnDomainId: 2.16.840.1.113883.3.704.100.200.1.1.3.1
  mrnDomainType: ISO
  mrnDomainLabel: My Health Compass
  mrnIdLength: 6
  mrnSystem: http://www.goodhealth.org/identifiers/mrn
  mrnUse: usual
  ssnSystem: http://hl7.org/fhir/v2/0203
  ssnLabel: SSN
fhir:
  serverUrl: https://open-api.fhir.me

---
spring:
  profiles: docker
server:
  ssl:
    key-store: /java/keystore/mhc.keystore
    key-store-password: changeit
security:
  oauth2:
    resource:
      user-info-uri: https://uaa.mhc:8443/uaa/userinfo
oauth:
  server:
    uaa: https://uaa.mhc:8443/uaa
  resources:
    phr: https://phr.mhc:8445/phr

